# Generated by Django 3.1.4 on 2021-01-11 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        ('spotify_api', '0002_auto_20210109_2027'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=70, unique=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('song_id', models.CharField(max_length=50)),
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='backend.room')),
            ],
        ),
    ]
