# Generated by Django 3.1.4 on 2021-01-06 18:30

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('code', models.CharField(default=backend.models.generate_unique_code, max_length=12, unique=True)),
                ('host', models.CharField(max_length=70, unique=True)),
                ('can_guest_pause', models.BooleanField(default=False)),
                ('votes_to_skip', models.SmallIntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
