# Generated by Django 3.1.4 on 2021-01-13 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20210112_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roomuser',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
