# Generated by Django 3.1.4 on 2021-01-14 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20210113_2200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_key', models.CharField(max_length=70, unique=True)),
                ('host_name', models.CharField(max_length=40)),
                ('host_url', models.CharField(max_length=120)),
            ],
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.host'),
        ),
    ]
